### ISSUE TITLE
Totally broken on my multi-monitor setup.

### ISSUE THREAD

**Issue by MarcelRobitaille** [jayk/window_grid#1]
First off, I just want to say how cool it is that you build this. I actually made something similar recently with way less features and hardcoded resolutions (because multimonitor seems hard).

As the title says, the script seems pretty broken on my 3-monitor setup. The readme says it supports multiple monitors so I thought I'd post an issue.

Not too sure what info you need.

Before:
![before](http://i.imgur.com/5LxSKQz.png)

After:
![after](http://i.imgur.com/vr88RC6.png)

Monitor configuration:
![monitor config](http://i.imgur.com/t7hnTMu.png)

`uname -a`:

    Linux Zeus 4.10.3-1-ARCH #1 SMP PREEMPT Wed Mar 15 09:17:17 CET 2017 x86_64 GNU/Linux

**Comment by jayk** [comment]
Hi!

Thanks for writing.  As of right now, you can address alternate monitors, but it's a little odd.  The x/y positions start on the first monitor.  I'm working on a reliable way to tell which monitor the window is on.  When I have that, I'll add it - but for now, since your screens are horizontal, the first monitor will start at X=0, the second monitor will start at X=8 and the third monitor will start at X=16.

so your command would be:

    window_grid -w 4 -h 4 -x 8 -y 0

**Comment by jayk** [comment]
Leaving this open until I get screen-specific selection working.

**Comment by jayk** [comment]
The most recent update makes window_grid properly screen-aware. Now x and y locations are relative to the display the window is on.

If you want to move windows from one screen to another, you can force the destination display by providing the -s # parameter.  where # is the display number (starting with 0)  Note that the screen number is based on the order displays are returned by xrandr,

Let me know if this works for you.
